### ISSUE TITLE
ipcluster badly killed

### ISSUE THREAD

**Issue by JeremyLGauthier** [dereneaton/ipyrad#334] opened 2019-04-16 05:10 UTC
Dear IpyRAD developers,

I work on a cluster under Ubuntu and I installed ipyrad using conda.
I ran ipyrad using nohup, this is a small cluster without SGE architecture or anything else. 

To stop a ipyrad job during the process, I dirtily killed the ipcluster processes using kill -9.

Unfortunately when I try to run again Ipyrad,  ipcluster doesn't seem to work, I can see it using top but nothing appends and the process is blocked at the clustering step (step3). 

Can something in the functioning of ipyrad explain this?

Thank you a lot ! 
Jeremy

**Comment by isaacovercast** [comment] 2019-04-16 13:33
When you submit an issue it's important to provide as much relevant detail as possible. What is the exact version of ipyrad and ipcluster you're using? If you killed ipcluster with -9, did you also clean up all the running engine processes (I assume not). If you killed ipcluster with -9, how did you stop ipyrad (I assume with ctrl+c)? When you say "I can see it using top" by "it" do you mean ipyrad or ipcluster? Did you try running step 3 with the `-f` command to force overwriting?

In the future, if you have a problem that you are not sure is really an ipyrad problem this could be more appropriate as a question for the [gitter channel](https://gitter.im/dereneaton/ipyrad).

Since it's not clear to me that this is a problem with ipyrad and not with your environment, and since there's not enough information for me to reproduce this problem I'm going to close this issue. If you do believe this is an ipyrad issue please provide more relevant info and reopen, otherwise just jump on the gitter channel and ask for help.

**Closed by isaacovercast** 2019-04-16 13:33 UTC
